version: '3'
services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    networks:
      - node-red-net
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

  MQTTbroker:
    image: eclipse-mosquitto:1.6.13
    restart: unless-stopped
    ports:
      - 1883:1883
    networks:
      - node-red-net


  
  esphome:
    image: ghcr.io/esphome/esphome
    container_name: esphome
    volumes:
      - ./code-server/workspace:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    # network_mode: host # nefunguje na macOS (Dejv)
    # environment:
      # login do UI ESPHome, muze se zakomentovat, jestli to nepotrebujes
      # - USERNAME=test
      # - PASSWORD=ChangeMe
    ports:
      - 6052:6052

volumes:
  node-red-data:

networks:
  node-red-net: